# Generated by Django 4.1.4 on 2024-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(unique=True)),
                ('invoiceDate', models.DateTimeField()),
                ('invoiceNumber', models.IntegerField(unique=True)),
                ('customerName', models.CharField(max_length=150)),
                ('billingAddress', models.TextField()),
                ('shippingAddress', models.TextField()),
                ('GSTIN', models.CharField(max_length=20)),
                ('TotalAmount', models.IntegerField()),
            ],
        ),
    ]
