# Generated by Django 4.1.4 on 2024-06-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceDate',
        ),
    ]
